"""导入所有模型，确保 Base.metadata 完整（供 Alembic autogenerate）。"""
from app.models.chat import ChatMessage, ChatSession
from app.models.data_quality import FactDataQualityIssue
from app.models.dimensions import DimCustomer, DimPart, DimSupplier, PartAlias
from app.models.inquiry import FPartInquiry
from app.models.inventory import Inventory, PartSubstitute
from app.models.maintenance import (
    FMaintenanceLine,
    FMaintenanceOrder,
    FProjectExpense,
    MaintenanceDemandDeleteEvent,
    MaintenanceDemandDeleteIntent,
    MaintenanceDemandDeleteIntentItem,
    MaintenanceDemandTombstone,
    MaintenanceContractWorkbookState,
    MaintenanceManualCostOverride,
    MaintenanceRoundtripOperation,
)
from app.models.maintenance_project import (
    MaintenanceProject,
    MaintenanceProjectAuditLog,
    MaintenanceProjectContract,
    MaintenanceProjectUserAssignment,
)
from app.models.maintenance_bad_return import (
    MaintenanceBadReturn,
    MaintenanceBadReturnCommand,
    MaintenanceBadReturnLine,
    MaintenanceReturnObligation,
)
from app.models.maintenance_source_assignment import MaintenanceSourceOrderAssignment
from app.models.maintenance_project_operations import (
    MaintenanceCollectionSnapshot,
    MaintenanceProjectExpenseAttribution,
    MaintenanceProjectOperationAudit,
    MaintenanceProjectWorkbookOperation,
    MaintenanceProjectWorkbookState,
    MaintenanceProjectWorkbookValidation,
    MaintenanceSiteIssue,
    MaintenanceSiteIssueCommand,
    MaintenanceSiteIssueDeliverySource,
    MaintenanceSiteIssueLine,
    MaintenanceSiteIssueReturnEvent,
)
from app.models.maintenance_manager import (
    BusinessFile,
    BusinessFileDownloadAudit,
    BusinessFileLink,
    MaintenanceAcceptanceOperation,
    MaintenanceAcceptanceDeliverable,
    MaintenanceCollectionMilestone,
    MaintenanceManagerUploadBatch,
    MaintenanceManagerUploadBatchProject,
    MaintenanceServicePeriod,
)
from app.models.maintenance_warehouse import (
    MaintenanceWarehouseAmbiguity,
    MaintenanceWarehouseAuditEvent,
    MaintenanceWarehouseDocument,
    MaintenanceWarehouseDocumentLine,
    MaintenanceWarehouseDocumentLink,
    MaintenanceWarehouseImportBatch,
)
from app.models.master_data import (
    Brand,
    ProductCategory,
    ProductDataQualityIssue,
    ProductMatchCandidate,
    ProductMergeLog,
    ProductSpec,
)
from app.models.purchase import FPurchaseLine, FPurchaseOrder
from app.models.sales import FSalesLine, FSalesOrder
from app.models.system import (
    SysAuditLog,
    SysBusinessSetting,
    SysImportBatch,
    SysImportError,
    SysImportJob,
    SysRawFile,
    SysRoleTemplate,
    SysUser,
)
from app.models.replenishment import (
    ReplenishmentApplication,
    ReplenishmentApplicationLine,
    ReplenishmentApplicationVersion,
    ReplenishmentAuditEvent,
    ReplenishmentReview,
    ReplenishmentReviewLine,
)

__all__ = [
    "ChatSession",
    "ChatMessage",
    "FactDataQualityIssue",
    "DimPart",
    "PartAlias",
    "DimSupplier",
    "DimCustomer",
    "Brand",
    "ProductCategory",
    "ProductSpec",
    "ProductMatchCandidate",
    "ProductMergeLog",
    "ProductDataQualityIssue",
    "FPurchaseOrder",
    "FPurchaseLine",
    "FMaintenanceOrder",
    "FMaintenanceLine",
    "MaintenanceDemandDeleteIntent",
    "MaintenanceDemandDeleteIntentItem",
    "MaintenanceDemandTombstone",
    "MaintenanceDemandDeleteEvent",
    "FProjectExpense",
    "MaintenanceContractWorkbookState",
    "MaintenanceManualCostOverride",
    "MaintenanceRoundtripOperation",
    "MaintenanceProject",
    "MaintenanceProjectAuditLog",
    "MaintenanceProjectContract",
    "MaintenanceProjectUserAssignment",
    "MaintenanceReturnObligation",
    "MaintenanceBadReturn",
    "MaintenanceBadReturnLine",
    "MaintenanceBadReturnCommand",
    "MaintenanceSourceOrderAssignment",
    "MaintenanceCollectionSnapshot",
    "MaintenanceProjectExpenseAttribution",
    "MaintenanceProjectOperationAudit",
    "MaintenanceProjectWorkbookOperation",
    "MaintenanceProjectWorkbookState",
    "MaintenanceProjectWorkbookValidation",
    "MaintenanceSiteIssue",
    "MaintenanceSiteIssueCommand",
    "MaintenanceSiteIssueDeliverySource",
    "MaintenanceSiteIssueLine",
    "MaintenanceSiteIssueReturnEvent",
    "MaintenanceManagerUploadBatch",
    "MaintenanceManagerUploadBatchProject",
    "MaintenanceServicePeriod",
    "MaintenanceCollectionMilestone",
    "MaintenanceAcceptanceDeliverable",
    "BusinessFile",
    "BusinessFileDownloadAudit",
    "BusinessFileLink",
    "MaintenanceAcceptanceOperation",
    "MaintenanceWarehouseImportBatch",
    "MaintenanceWarehouseDocument",
    "MaintenanceWarehouseDocumentLine",
    "MaintenanceWarehouseDocumentLink",
    "MaintenanceWarehouseAmbiguity",
    "MaintenanceWarehouseAuditEvent",
    "FSalesOrder",
    "FSalesLine",
    "Inventory",
    "PartSubstitute",
    "FPartInquiry",
    "SysImportBatch",
    "SysImportError",
    "SysImportJob",
    "SysRawFile",
    "SysAuditLog",
    "SysBusinessSetting",
    "SysUser",
    "SysRoleTemplate",
    "ReplenishmentApplication",
    "ReplenishmentApplicationVersion",
    "ReplenishmentApplicationLine",
    "ReplenishmentReview",
    "ReplenishmentReviewLine",
    "ReplenishmentAuditEvent",
]
