"""Stable-project operating facts independent from the legacy WBDD read model."""

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    Date,
    LargeBinary,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base
from app.models._types import Money, Qty, TZDateTime


class MaintenanceCollectionSnapshot(Base):
    """One contract's cumulative collection value for one reporting month."""

    __tablename__ = "maintenance_collection_snapshot"

    collection_id: Mapped[str] = mapped_column(String(36), primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project.project_id"), nullable=False
    )
    project_contract_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project_contract.project_contract_id"), nullable=False
    )
    report_month: Mapped[date] = mapped_column(Date, nullable=False)
    cumulative_amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False)
    receipt_reference: Mapped[str | None] = mapped_column(String(128))
    remark: Mapped[str | None] = mapped_column(Text)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('confirmed', 'unconfirmed', 'void')",
            name="ck_maintenance_collection_status",
        ),
        CheckConstraint(
            "cumulative_amount >= 0 AND cumulative_amount < 1000000000000",
            name="ck_maintenance_collection_amount",
        ),
        CheckConstraint("version >= 1", name="ck_maintenance_collection_version"),
        CheckConstraint(
            "report_month = date_trunc('month', report_month)::date",
            name="ck_maintenance_collection_month_start",
        ),
        UniqueConstraint(
            "project_contract_id",
            "report_month",
            name="uq_maintenance_collection_contract_month",
        ),
        Index(
            "ix_maintenance_collection_project_month",
            "project_id",
            "report_month",
        ),
    )


class MaintenanceProjectOperationAudit(Base):
    """Audit log for project-scoped operating facts with string identifiers."""

    __tablename__ = "maintenance_project_operation_audit"

    id: Mapped[int] = mapped_column(primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project.project_id"), nullable=False
    )
    entity_type: Mapped[str] = mapped_column(String(32), nullable=False)
    entity_id: Mapped[str] = mapped_column(String(64), nullable=False)
    action: Mapped[str] = mapped_column(String(32), nullable=False)
    before_json: Mapped[dict | None] = mapped_column(JSONB)
    after_json: Mapped[dict | None] = mapped_column(JSONB)
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    operated_by: Mapped[str] = mapped_column(String(64), nullable=False)
    operated_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "char_length(btrim(reason)) > 0",
            name="ck_maintenance_project_operation_audit_reason",
        ),
        CheckConstraint(
            "char_length(btrim(operated_by)) > 0",
            name="ck_maintenance_project_operation_audit_operator",
        ),
        Index(
            "ix_maintenance_project_operation_audit_project_time",
            "project_id",
            "operated_at",
            "id",
        ),
    )


class MaintenanceSiteIssue(Base):
    """Canonical, status-mapped site issue generated by the monthly workbook."""

    __tablename__ = "maintenance_site_issue"

    issue_id: Mapped[str] = mapped_column(String(36), primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project.project_id"), nullable=False
    )
    issue_no: Mapped[str] = mapped_column(String(64), nullable=False)
    issue_date: Mapped[date] = mapped_column(Date, nullable=False)
    raw_status: Mapped[str] = mapped_column(String(64), nullable=False)
    status_mapping_state: Mapped[str] = mapped_column(String(16), nullable=False)
    normalized_status: Mapped[str] = mapped_column(String(16), nullable=False)
    status_mapping_version: Mapped[str] = mapped_column(String(64), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "status_mapping_state IN ('mapped', 'unmapped')",
            name="ck_maintenance_site_issue_mapping_state",
        ),
        CheckConstraint(
            "normalized_status IN ('confirmed', 'void', 'unknown')",
            name="ck_maintenance_site_issue_normalized_status",
        ),
        CheckConstraint(
            "status_mapping_state = 'mapped' OR normalized_status = 'unknown'",
            name="ck_maintenance_site_issue_unmapped_unknown",
        ),
        CheckConstraint("version >= 1", name="ck_maintenance_site_issue_version"),
        UniqueConstraint("project_id", "issue_no", name="uq_maintenance_site_issue_project_no"),
        Index("ix_maintenance_site_issue_project_date", "project_id", "issue_date"),
    )


class MaintenanceSiteIssueLine(Base):
    """One actual site-consumption line and its reproducible pricing evidence."""

    __tablename__ = "maintenance_site_issue_line"

    issue_line_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    issue_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_site_issue.issue_id"), nullable=False
    )
    line_no: Mapped[int] = mapped_column(Integer, nullable=False)
    part_id: Mapped[int] = mapped_column(ForeignKey("dim_part.id"), nullable=False)
    pn: Mapped[str] = mapped_column(String(128), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Qty, nullable=False)
    linked_purchase_line_id: Mapped[int | None] = mapped_column(
        ForeignKey("f_purchase_line.id")
    )
    manual_unit_cost: Mapped[Decimal | None] = mapped_column(Money)
    manual_evidence: Mapped[str | None] = mapped_column(Text)
    unit_cost: Mapped[Decimal | None] = mapped_column(Money)
    cost_amount: Mapped[Decimal | None] = mapped_column(Money)
    cost_source: Mapped[str | None] = mapped_column(String(24))
    price_basis: Mapped[str] = mapped_column(
        String(16), nullable=False, default="ex_tax", server_default="ex_tax"
    )
    reference_side: Mapped[str | None] = mapped_column(String(16))
    reference_sample_ids: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list, server_default="[]"
    )
    reference_sample_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
    reference_samples: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list, server_default="[]"
    )
    reference_window_from: Mapped[date | None] = mapped_column(Date)
    reference_window_to: Mapped[date | None] = mapped_column(Date)
    algorithm_version: Mapped[str] = mapped_column(String(64), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "quantity > 0 AND quantity < 1000000000000",
            name="ck_maintenance_site_issue_line_quantity",
        ),
        CheckConstraint(
            "manual_unit_cost IS NULL OR (manual_unit_cost >= 0 AND manual_unit_cost < 1000000000000)",
            name="ck_maintenance_site_issue_line_manual_cost",
        ),
        CheckConstraint(
            "unit_cost IS NULL OR (unit_cost >= 0 AND unit_cost < 1000000000000)",
            name="ck_maintenance_site_issue_line_unit_cost",
        ),
        CheckConstraint(
            "cost_source IS NULL OR cost_source IN ('direct_purchase', 'purchase_window', 'sales_window', 'manual')",
            name="ck_maintenance_site_issue_line_cost_source",
        ),
        CheckConstraint(
            "(manual_unit_cost IS NULL) = (manual_evidence IS NULL)",
            name="ck_maintenance_site_issue_line_manual_evidence_pair",
        ),
        CheckConstraint(
            "(cost_source IS NULL AND unit_cost IS NULL AND cost_amount IS NULL) OR "
            "(cost_source IS NOT NULL AND unit_cost IS NOT NULL AND cost_amount IS NOT NULL)",
            name="ck_maintenance_site_issue_line_cost_result_pair",
        ),
        CheckConstraint(
            "price_basis = 'ex_tax'",
            name="ck_maintenance_site_issue_line_price_basis",
        ),
        CheckConstraint(
            "reference_sample_count = jsonb_array_length(reference_samples)",
            name="ck_maintenance_site_issue_line_sample_evidence_count",
        ),
        CheckConstraint(
            "char_length(btrim(algorithm_version)) > 0",
            name="ck_maintenance_site_issue_line_algorithm_version",
        ),
        CheckConstraint("reference_sample_count >= 0", name="ck_maintenance_site_issue_line_sample_count"),
        CheckConstraint("version >= 1", name="ck_maintenance_site_issue_line_version"),
        UniqueConstraint("issue_id", "line_no", name="uq_maintenance_site_issue_line_no"),
        Index("ix_maintenance_site_issue_line_issue", "issue_id", "line_no"),
        Index("ix_maintenance_site_issue_line_part", "part_id"),
    )


class MaintenanceProjectExpenseAttribution(Base):
    """Canonical expense attribution; only mapped+approved facts count."""

    __tablename__ = "maintenance_project_expense_attribution"

    expense_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project.project_id"), nullable=False
    )
    project_contract_id: Mapped[str | None] = mapped_column(
        ForeignKey("maintenance_project_contract.project_contract_id")
    )
    expense_ref: Mapped[str] = mapped_column(String(128), nullable=False)
    expense_date: Mapped[date] = mapped_column(Date, nullable=False)
    applicant: Mapped[str | None] = mapped_column(String(64))
    category: Mapped[str | None] = mapped_column(String(64))
    expense_reason: Mapped[str | None] = mapped_column(Text)
    amount_ex_tax: Mapped[Decimal] = mapped_column(Money, nullable=False)
    raw_status: Mapped[str] = mapped_column(String(64), nullable=False)
    status_mapping_state: Mapped[str] = mapped_column(String(16), nullable=False)
    normalized_status: Mapped[str] = mapped_column(String(16), nullable=False)
    status_mapping_version: Mapped[str] = mapped_column(String(64), nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "status_mapping_state IN ('mapped', 'unmapped')",
            name="ck_maintenance_project_expense_mapping_state",
        ),
        CheckConstraint(
            "normalized_status IN ('approved', 'rejected', 'void', 'unknown')",
            name="ck_maintenance_project_expense_status",
        ),
        CheckConstraint(
            "status_mapping_state = 'mapped' OR normalized_status = 'unknown'",
            name="ck_maintenance_project_expense_unmapped_unknown",
        ),
        CheckConstraint(
            "amount_ex_tax >= 0 AND amount_ex_tax < 1000000000000",
            name="ck_maintenance_project_expense_amount",
        ),
        CheckConstraint("version >= 1", name="ck_maintenance_project_expense_version"),
        UniqueConstraint("project_id", "expense_ref", name="uq_maintenance_project_expense_ref"),
        Index(
            "ix_maintenance_project_expense_project_date",
            "project_id",
            "expense_date",
        ),
    )


class MaintenanceProjectWorkbookState(Base):
    """Project-level concurrency token for the generated four-sheet workbook."""

    __tablename__ = "maintenance_project_workbook_state"

    project_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project.project_id"), primary_key=True
    )
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    last_export_id: Mapped[str | None] = mapped_column(String(64))
    last_exported_at: Mapped[datetime | None] = mapped_column(TZDateTime)
    last_applied_at: Mapped[datetime | None] = mapped_column(TZDateTime)
    data_version: Mapped[str] = mapped_column(String(64), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        CheckConstraint("revision >= 0", name="ck_maintenance_project_workbook_state_revision"),
    )


class MaintenanceProjectWorkbookOperation(Base):
    """Idempotency/audit record for project-workbook exports and applies."""

    __tablename__ = "maintenance_project_workbook_operation"

    id: Mapped[int] = mapped_column(primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project.project_id"), nullable=False
    )
    export_id: Mapped[str | None] = mapped_column(String(64))
    file_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    operation_key: Mapped[str] = mapped_column(String(128), nullable=False)
    payload_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    operation_type: Mapped[str] = mapped_column(String(24), nullable=False)
    operated_by: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now()
    )

    __table_args__ = (
        CheckConstraint(
            "operation_type IN ('collection_create', 'file_export', 'file_apply')",
            name="ck_maintenance_project_workbook_operation_type",
        ),
        UniqueConstraint(
            "operation_key",
            name="uq_maintenance_project_workbook_operation_key",
        ),
        Index(
            "ix_maintenance_project_workbook_operation_project_file",
            "project_id",
            "file_sha256",
        ),
    )


class MaintenanceProjectWorkbookValidation(Base):
    """Server-owned, expiring validation plan used by atomic workbook apply."""

    __tablename__ = "maintenance_project_workbook_validation"

    validation_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ForeignKey("maintenance_project.project_id"), nullable=False
    )
    export_id: Mapped[str] = mapped_column(String(64), nullable=False)
    expected_revision: Mapped[int] = mapped_column(Integer, nullable=False)
    file_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    plan_json: Mapped[dict | None] = mapped_column(JSONB)
    status: Mapped[str] = mapped_column(String(16), nullable=False)
    issues_json: Mapped[list] = mapped_column(
        JSONB, nullable=False, default=list, server_default="[]"
    )
    error_workbook: Mapped[bytes | None] = mapped_column(LargeBinary)
    created_by: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        TZDateTime, nullable=False, server_default=func.now()
    )
    expires_at: Mapped[datetime] = mapped_column(TZDateTime, nullable=False)
    applied_at: Mapped[datetime | None] = mapped_column(TZDateTime)

    __table_args__ = (
        CheckConstraint("expected_revision >= 0", name="ck_maintenance_project_workbook_validation_revision"),
        CheckConstraint(
            "status IN ('valid', 'error', 'applied', 'expired')",
            name="ck_maintenance_project_workbook_validation_status",
        ),
        CheckConstraint(
            "error_workbook IS NULL OR status = 'error'",
            name="ck_maintenance_project_workbook_validation_error_file_status",
        ),
        CheckConstraint(
            "plan_json IS NULL OR status IN ('valid', 'applied')",
            name="ck_maintenance_project_workbook_validation_plan_status",
        ),
        CheckConstraint(
            "error_workbook IS NULL OR octet_length(error_workbook) <= 5242880",
            name="ck_maintenance_project_workbook_validation_error_file_size",
        ),
        Index("ix_maintenance_project_workbook_validation_expires", "expires_at"),
        Index(
            "ix_maintenance_project_workbook_validation_project_file",
            "project_id",
            "file_sha256",
        ),
    )
