"""剩余类目黄金测试（主板/背板/RAID·HBA/NIC·FC/其他卡/电源/电池/风扇/光模块/线缆/耗材）。
真实数据驱动设计 + 对抗验证（workflow），每条钉死「无证据不猜、分类由字段决定、缺关键字段转人工」。"""
import pytest

from app.services import standardize as S

# (id, pn, description, brand, expected_canonical, expected_l2_name, expected_review_status)
CASES = [
    ('mainboard-1', '', 'HP DL360p.Gen8主板', '惠普（HPE）', 'HPE DL360p Gen8 System Board', '系统主板', 'AUTO_OK'),
    ('mainboard-2', '', 'HP Gen7 DL380 System Board', '惠普（HPE）', 'HPE DL380 System Board', '系统主板', 'AUTO_OK'),
    ('mainboard-3', '', 'DELL System Board For R820', '戴尔（DELL）', 'Dell R820 System Board', '系统主板', 'AUTO_OK'),
    ('mainboard-4', '', 'IBM System Board For X3550M5', '联想（IBM）', 'Lenovo X3550M5 System Board', '系统主板', 'AUTO_OK'),
    ('mainboard-5', '', 'IBM Socket FCLGA2011-3 Intel Chipset System Board Motherboard for X3650 M5 Supports 2x Xeon E5-2600 V3 Series DDR4 24x DIMM', '联想（IBM）', 'Lenovo X3650 M5 System Board', '系统主板', 'AUTO_OK'),
    ('mainboard-6', '', 'IBM 01GT572 x3650M5 System Board (5462)', '联想（IBM）', 'Lenovo x3650M5 System Board', '系统主板', 'AUTO_OK'),
    ('mainboard-7', '', 'hp 主板', '惠普（HPE）', None, None, 'REVIEW_REQUIRED'),
    ('mainboard-8', '', '网络>交换机 ZXR10 ZXJ10 板卡-主板/系统板  SYCK 时钟同步板', '其他', 'ZXR10 System Board', '系统主板', 'REVIEW_REQUIRED'),
    ('backplane-1', 'BP-FH-24', '烽火  24盘位硬盘背板 2U 2.5寸', '烽火（Fiberhome）', '24-Bay 2.5-inch Drive Backplane', '背板', 'AUTO_OK'),
    ('backplane-2', 'BP-HP-G10', 'HP SAS 12Gb/s 8 SFF 2.5-inch Backplane for ProLiant DL380 G10', '惠普（HPE）', 'HPE 8-Bay 2.5-inch SAS Drive Backplane', '背板', 'AUTO_OK'),
    ('backplane-3', 'BP-DELL-R730', 'DELL Disk BackPlane 24-port 2.5 SAS For R730XD', '戴尔（DELL）', 'Dell 24-Bay 2.5-inch SAS Drive Backplane', '背板', 'AUTO_OK'),
    ('backplane-4', 'BP-HP-BL460', 'HP Disk Backplane SAS/SATA 2-Slot BL460cG6', '惠普（HPE）', 'HPE 2-Bay SAS/SATA Drive Backplane', '背板', 'AUTO_OK'),
    ('backplane-5', 'BP-HW-RH2288', 'Huawei RH2288H V5 20x2.5英寸硬盘配置（8xSAS/SATA+12xNVMe）背板', '华为（HUAWEI）', 'Huawei 20-Bay 2.5-inch Drive Backplane', '背板', 'AUTO_OK'),
    ('backplane-6', 'BP-SUGON-PWR', 'Sugon Power Backplane For i840r-GP', '中科曙光（Sugon）', 'Power Backplane', '背板', 'AUTO_OK'),
    ('backplane-7', 'BP-DELL-MID', 'DELL Midplane For M1000E', '戴尔（DELL）', 'Dell Midplane', '背板', 'AUTO_OK'),
    ('backplane-8', 'BP-DELL-CABLE', 'DELL 硬盘背板连接线 for R720', '戴尔（DELL）', None, None, 'REVIEW_REQUIRED'),
    ('raid_hba-1', '', 'HPE Z Smart Array P440ar 12Gb Ctrlr', '亿泰兴电子（Etasis）', 'HPE Smart Array P440ar 12Gb/s RAID Controller', '阵列卡RAID', 'AUTO_OK'),
    ('raid_hba-2', '', 'DELL Perc H710P Adapter 1GB Cach 6Gbp/s SAS PCI-E High Profile R820', '戴尔（DELL）', 'Dell Perc H710P SAS 6Gb/s 1GB Cache RAID Controller', '阵列卡RAID', 'AUTO_OK'),
    ('raid_hba-3', '', 'Lenovo LSI SAS 9311-8i PCIe SAS HBA 12Gb', '联想（Lenovo）2', 'Lenovo 9311-8i SAS 12Gb/s 8i HBA', 'HBA卡', 'AUTO_OK'),
    ('raid_hba-4', '', '华为  LSI SAS 9300-8i 12Gb/s HBA通道卡', '华为（HUAWEI）', 'Huawei 9300-8i SAS 12Gb/s 8i HBA', 'HBA卡', 'AUTO_OK'),
    ('raid_hba-5', '', 'LSI HBA 9400-8e SAS3408 PCIe3.1(NVMe) 12Gb/s', '艾萨华（LSI）', '9400-8e SAS 12Gb/s 8e PCIe 3.0 HBA', 'HBA卡', 'AUTO_OK'),
    ('raid_hba-6', '', 'DELL HBA330+ 12GB/s LP PCI-E x8 Host BUS Adapter J7TNV', '戴尔（DELL）', 'Dell HBA330+ SAS 12Gb/s HBA', 'HBA卡', 'AUTO_OK'),
    ('raid_hba-7', '', 'HP HBA PCI-E 2-Port 8G FC', '惠普（HPE）', 'HPE 2-Port 8GFC Fibre Channel HBA', '光纤卡FC', 'AUTO_OK'),
    ('raid_hba-8', '', 'Micron 2300 M.2 2280 512GB MTFDHBA512TDV SSD', '镁光（Micron）', None, None, 'REVIEW_REQUIRED'),
    ('nic_fc-1', '', 'Intel Single SFP+ Port 10GbE Network Adapter(NIC), 82599ES PCI-E X8,', '英特尔（INTEL）', 'Intel 1-Port 10GbE SFP+ NIC', '网卡NIC', 'AUTO_OK'),
    ('nic_fc-2', '', 'Mellanox CX4421A ConnectX-4 Lx Dual Port 25GbE SFP+ Mezzanine Network Adapter', '迈络思（Mellanox）', 'NVIDIA 2-Port 25GbE SFP+ NIC', '网卡NIC', 'AUTO_OK'),
    ('nic_fc-3', '', 'Huawei SP380 Ethernet Adapter,25GE(Mellanox CX-4 Lx),Dual-Port,', '华为（HUAWEI）', 'Huawei 2-Port 25GbE NIC', '网卡NIC', 'AUTO_OK'),
    ('nic_fc-4', '', '02570037 BC5M07ETHE SP380 25Gb SFP28 双端口万兆光纤网卡', '其他', '2-Port 25GbE SFP28 NIC', '网卡NIC', 'AUTO_OK'),
    ('nic_fc-5', '', 'HPE 868140-001 StoreFabric SN1600Q 1-Port Fibre Channel 32Gb/s PCI HBA', '惠普（HPE）', 'HPE 1-Port 32GFC Fibre Channel HBA', '光纤卡FC', 'AUTO_OK'),
    ('nic_fc-6', '', 'QLogic HBA PCI-E 2-Port 8G FC', '纳斯达克（Qlogic）', 'Marvell 2-Port 8GFC Fibre Channel HBA', '光纤卡FC', 'AUTO_OK'),
    ('nic_fc-7', '', 'Emulex LightPulse LPe32002-M2 P011324-21G 双端口 32Gb', 'Emulex', 'Broadcom 2-Port 32GFC Fibre Channel HBA', '光纤卡FC', 'AUTO_OK'),
    ('nic_fc-8', '', 'QLogic 16 Port Stackable Fibre Channel Switch Module SB9000', '纳斯达克（Qlogic）', None, '光纤卡FC', 'REVIEW_REQUIRED'),
    ('other_card-1', 'PN-OC-01', '03023PCP  BC61RISB  PCIE 16X riser卡 扩展卡', '华为（HUAWEI）', 'Huawei BC61RISB Riser Card', '其他适配卡', 'AUTO_OK'),
    ('other_card-2', 'PN-OC-02', 'DELL 0MDDTD Riser Card Server PowerEdge R740', '戴尔（DELL）', 'Dell 0MDDTD Riser Card', '其他适配卡', 'AUTO_OK'),
    ('other_card-3', 'PN-OC-03', '华为扣卡03022YMY IT11MXEM 华为 MZ310,2*10G Mezzanine Card', '华为（HUAWEI）', 'Huawei IT11MXEM Mezzanine Card', '其他适配卡', 'AUTO_OK'),
    ('other_card-4', 'PN-OC-04', '浪潮AS5600G2 存储SAS扩展卡', '浪潮（Inspur）', 'Inspur Expansion Card', '其他适配卡', 'AUTO_OK'),
    ('other_card-5', 'PN-OC-05', 'DELL RISER CARD', '戴尔（DELL）', 'Dell Riser Card', '其他适配卡', 'AUTO_OK'),
    ('other_card-6', 'PN-OC-06', '1288H-V5 PCI扩展卡', '华为（HUAWEI）', 'Huawei Expansion Card', '其他适配卡', 'AUTO_OK'),
    ('other_card-7', 'PN-OC-07', '03026CMN BC82PRUF Oceanstor 9000 V5 PCIE RISER BOARD', '华为（TaiShan）', 'Huawei BC82PRUF Riser Card', '其他适配卡', 'AUTO_OK'),
    ('other_card-8', 'PN-OC-08', 'DELL R720 整机扩展卡', '戴尔（DELL）', 'Dell Expansion Card', '其他适配卡', 'AUTO_OK'),
    ('psu-1', 'PSU-450-001', '450W AC Power Supply Module', '其他', '450W AC Power Supply', None, 'AUTO_OK'),
    ('psu-2', 'PSU-HPE-1200', 'HP Power Supply 1200W AC Hot-Plug 89% Efficiency', '惠普（HPE）', 'HPE 1200W AC Hot-Plug Power Supply', None, 'AUTO_OK'),
    ('psu-3', 'PSU-EMC-400', 'EMC Power Supply 400W AC Hot-Sawp VNX DAE3U', '易安信（EMC）', 'EMC 400W AC Hot-Plug Power Supply', None, 'AUTO_OK'),
    ('psu-4', 'PSU-FUJ-2000', 'Fujitsu Power Supply 2000W AC For Dx8700 S2', '富士通（Fujitsu）', 'Fujitsu 2000W AC Power Supply', None, 'AUTO_OK'),
    ('psu-5', 'PSU-LEN-1100', 'ThinkSystem 1100W (230V/115V) Platinum HS PSU', '联想（Lenovo）', 'Lenovo 1100W Hot-Plug Power Supply', None, 'AUTO_OK'),
    ('psu-6', 'PSU-ORA-495', 'Oracle  ACME Packet 3900 /ARTESYN  Power supply 495W', '甲骨文（Oracle）', 'Oracle 495W Power Supply', None, 'AUTO_OK'),
    ('psu-7', 'PSU-H3C-650', 'H3C Power Supply 650W AC Hot-plug For S7006E', '新华三（H3C）', 'H3C 650W AC Hot-Plug Power Supply', None, 'AUTO_OK'),
    ('psu-8', 'PSU-INS-1300', 'Inspur Power Supply 1300W AC', '浪潮（Inspur）', 'Inspur 1300W AC Power Supply', None, 'AUTO_OK'),
    ('battery-1', 'L3-25034', 'Lsi Battery 13.5V 6.4F', '艾萨华（LSI）', '13.5V Battery', '电池/超级电容', 'AUTO_OK'),
    ('battery-2', 'P0001', 'HP 96W Smart Storage Battery', '惠普（HPE）', 'HPE Smart Storage Battery', '电池/超级电容', 'AUTO_OK'),
    ('battery-3', 'CGA103450A', 'Panasonic Battery 3V Lithium Coin', '松下（Panasonic）', '3V CMOS Battery', '电池/超级电容', 'AUTO_OK'),
    ('battery-4', '0231Y384', 'Huawei 0231Y384 Raid Card Super Cap', '华为（HUAWEI）', 'Huawei Supercapacitor', '电池/超级电容', 'AUTO_OK'),
    ('battery-5', 'P840AR', 'HP Smart Array P840ar/2GB FBWC 12GB 2-port Internal SAS Controller Ref', '惠普（HPE）', 'HPE FBWC Module', '电池/超级电容', 'AUTO_OK'),
    ('battery-6', 'BC1MO0ESMP', '华为 XH628 V3 SR430C-ML 1G-BC1MO0ESMP-LSI 3108 RAID卡电池', '华为（HUAWEI）', 'Huawei RAID Cache Battery', '电池/超级电容', 'AUTO_OK'),
    ('battery-7', '18500V3-BBU', '华为OceanStor 18500V3 BBU', '华为（HUAWEI）', 'Huawei BBU', '电池/超级电容', 'AUTO_OK'),
    ('battery-8', 'MM-NVRAM', 'Curtiss-Wright Micro Memory NVRAM 1gb Mezzanine Battery', '其他', 'NVRAM Battery', '电池/超级电容', 'AUTO_OK'),
    ('fan-1', '', 'Mellanox Fan module w/rear to front airflow fan for SB77X0', '迈络思（Mellanox）', 'Fan Module', '风扇/散热', 'AUTO_OK'),
    ('fan-2', '', 'Dell FAN BackPlane For R920', '戴尔（DELL）', 'Dell Fan Backplane', '风扇/散热', 'AUTO_OK'),
    ('fan-3', '', 'IBM Heat sink 7944.X3550M3(all models)', '联想（IBM）', 'Lenovo Heatsink', '风扇/散热', 'AUTO_OK'),
    ('fan-4', '', 'Xyratex Fan Hot-Plug RS1220', '希捷（Xyratex）', 'Seagate Hot-Plug Fan', '风扇/散热', 'AUTO_OK'),
    ('fan-5', '', 'IBM H70 BLOWER ASSEMBLY', '联想（IBM）', 'Lenovo Blower', '风扇/散热', 'AUTO_OK'),
    ('fan-6', '', 'Lenovo 2U 6038 fan module for RD450', '联想（Lenovo）', 'Lenovo Fan Module', '风扇/散热', 'AUTO_OK'),
    ('fan-7', '', 'Catalyst 4506 4500交换机风扇', '思科（Cisco）', 'Cisco Fan', '风扇/散热', 'AUTO_OK'),
    ('fan-8', '', 'HP 580W POWER COOLING MODULE 0960991-14', '惠普（HPE）', None, None, 'REVIEW_REQUIRED'),
    ('optics-1', '', 'SUN ORACLE AFBR-79E4Z-SN2 Sun 40GBase-SR4 FRU135-1204-01', '甲骨文（SUN）', None, None, 'REVIEW_REQUIRED'),
    ('optics-2', '', 'Lenovo 40GBASE-iSR4 QSFP+ Transceiver', '联想（Lenovo）', 'Lenovo 40G QSFP+ iSR4 Optical Transceiver', '光模块', 'AUTO_OK'),
    ('optics-3', '', '100G QSFP28光模块', '其他', '100G QSFP28 Optical Transceiver', '光模块', 'AUTO_OK'),
    ('optics-4', '', 'HuaWei SFP 10Gb/s 850nm SFP+ 0.3KM  LC MM -7.3dBm-9.9dBm', '华为（HUAWEI）2', 'Huawei 10G SFP+ 850nm 0.3km LC MMF Optical Transceiver', '光模块', 'AUTO_OK'),
    ('optics-5', '', 'XG-SFP-LR-SM1310 10GBASE-LR SFP+ 1310-nm 10-km DOM Duplex LC SMF Optical Transceiver Module', '锐捷网络（Ruijie）', '10G SFP+ LR 1310nm 10km LC SMF Optical Transceiver', '光模块', 'AUTO_OK'),
    ('optics-6', '', 'Avago AFCT-57R5ATPZ 4.25Gbps 1310nm 10km TXRX OPT SFP', '安华高（Avago）', None, None, 'REVIEW_REQUIRED'),
    ('optics-7', '', 'LINKTEL LX6501CDH 25G 850nm 70m SFP28光模块', '其他', '25G SFP28 850nm 70m Optical Transceiver', '光模块', 'AUTO_OK'),
    ('optics-8', '', 'Intel X520-Da2 Ethernet 10Gbps Dual Port Sfp+ Pci-E Card', '英特尔（INTEL）', None, None, 'REVIEW_REQUIRED'),
    ('cable-1', 'MFA2P10-A003', 'Mellanox MFA2P10-A003 Compatible SFP28 Active Optical Cable 25G 3m', '迈络思（Mellanox）', '25Gb/s SFP28 3m AOC Cable', '线缆', 'AUTO_OK'),
    ('cable-2', 'MCP1700-B003E', 'Mellanox MCP1700-B003E Compatible 40G QSFP+ Passive Direct Attach Copper Twinax Cable', '迈络思（Mellanox）', '40Gb/s QSFP+ DAC Cable', '线缆', 'AUTO_OK'),
    ('cable-3', 'MC2207130', 'MELLANOX Passive Copper cable, IB EDR, up to 100Gb/s, QSFP28, 3m', '迈络思（Mellanox）', '100Gb/s QSFP28 3m DAC Cable', '线缆', 'AUTO_OK'),
    ('cable-4', '00AN059', 'IBM SAS Cable SFF-8087 - SFF-8643 66cm System x3750 M4 - 00AN059 46W1499', '联想（IBM）', 'Lenovo SFF-8087 to SFF-8643 0.66m Mini-SAS HD Cable', '线缆', 'AUTO_OK'),
    ('cable-5', 'EMC-HDX4', 'EMC cable  Mini HDX4 SAS SFF-8644 to Mini SAS SFF-8088 2m', '易安信（EMC）', 'EMC SFF-8644 to SFF-8088 2m Mini-SAS Cable', '线缆', 'AUTO_OK'),
    ('cable-6', '286496-001', 'HP 286496-001 ProLiant Power cord C13 to China 2.1', '惠普（HPE）', 'HPE Power Cord', '线缆', 'AUTO_OK'),
    ('cable-7', 'QK733A', '15米 LC-LC万兆多模光纤线缆 for CE6851-48S6Q-HI', '新华三（H3C）', 'H3C LC-LC 15m Fiber Jumper Cable', '线缆', 'AUTO_OK'),
    ('cable-8', 'FC-SMP-2', 'IBM Cable SMP right long 2 cable', '联想（IBM）', None, None, 'REVIEW_REQUIRED'),
    ('misc-1', 'G-MISC-01', 'DELL.R730XD.Chassis', '戴尔（DELL）', '戴尔（Dell） Chassis', '其他备件/耗材', 'AUTO_OK'),
    ('misc-2', 'G-MISC-02', '• 2-Slot Bracket with Latch', '甲骨文（Oracle）', '甲骨文（Oracle） Bracket', '其他备件/耗材', 'AUTO_OK'),
    ('misc-3', 'G-MISC-03', 'HP DVD/CD 8x24x DVD-ROM Drive', '惠普（HPE）', '惠普（HPE） Optical Drive', '其他备件/耗材', 'AUTO_OK'),
    ('misc-4', 'G-MISC-04', 'CHASSIS 3.5" M5 12HDD', '其他', 'Chassis', '其他备件/耗材', 'AUTO_OK'),
    ('misc-5', 'G-MISC-05', 'PowerEdge R740 Sliding Rail Kit', '戴尔（DELL）', '戴尔（Dell） Rail Kit', '其他备件/耗材', 'AUTO_OK'),
    ('misc-6', 'G-MISC-06', 'Front Bezel with Lock for DL380 Gen10', '惠普（HPE）', '惠普（HPE） Bezel', '其他备件/耗材', 'AUTO_OK'),
    ('misc-7', 'G-MISC-07', 'EMC 118000526 SMART X10 DRV 64GB MLC M.2 6G ISILON UNITY', '易安信（EMC）', None, None, 'REVIEW_REQUIRED'),
    ('misc-8', 'G-MISC-08', 'ThinkSystem SR650 Air Baffle', '联想（Lenovo）', 'Lenovo Air Baffle', '风扇/散热', 'AUTO_OK'),
    ('misc-9', 'G-MISC-09', 'EMC Storage Chassis', '易安信（EMC）', '易安信（EMC） Chassis', '其他备件/耗材', 'AUTO_OK'),
    # 信息守恒回归（真实事故：IBM 磁带机被压成 '联想（Lenovo） Drive Caddy' 且自动通过）——
    # ①'with Caddy' 是附件提及不取本体 ②磁带机/TB 容量特征词 ③品牌字段(联想)与描述(IBM)冲突 → 转人工
    ('misc-10', '3592-55F', 'IBM 3592-55F TS1155 FC 8Gb Tape Drive with Caddy for 3584 TS4500 15TB 45TB',
     '联想（IBM）', None, None, 'REVIEW_REQUIRED'),
    ('misc-11', 'G-MISC-11', 'DELL 2.5寸硬盘托架 R730', '戴尔（DELL）', '戴尔（Dell） Drive Caddy', '其他备件/耗材', 'AUTO_OK'),
    ('misc-12', 'G-MISC-12', 'IBM LTO7 Tape Drive Module', '联想（IBM）', None, None, 'REVIEW_REQUIRED'),
    ('misc-13', 'G-MISC-13', 'HP DL380 Gen9 Caddy 2.5', '惠普（HPE）', '惠普（HPE） Drive Caddy', '其他备件/耗材', 'AUTO_OK'),
]


@pytest.mark.parametrize("cid,pn,desc,brand,exp_canon,exp_l2,exp_status",
                         CASES, ids=[c[0] for c in CASES])
def test_category_golden(cid, pn, desc, brand, exp_canon, exp_l2, exp_status):
    r = S.standardize(pn, desc, brand)
    assert r["canonical_description"] == exp_canon
    assert r["review_status"] == exp_status
    if exp_l2 is not None:
        assert r["category_l2"] == exp_l2
