"""add dim_part is_excluded

Revision ID: 876dad34e9c5
Revises: 9ab193c1387c
Create Date: 2026-05-27 17:27:55.747357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876dad34e9c5'
down_revision: Union[str, Sequence[str], None] = '9ab193c1387c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_part', sa.Column('is_excluded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('dim_part', sa.Column('exclude_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_part', 'exclude_reason')
    op.drop_column('dim_part', 'is_excluded')
    # ### end Alembic commands ###
