"""add fifo/moving cost columns

Revision ID: 9ab193c1387c
Revises: fb60839c775d
Create Date: 2026-05-22 18:04:01.115966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab193c1387c'
down_revision: Union[str, Sequence[str], None] = 'fb60839c775d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('f_sales_line', sa.Column('cost_moving_avg', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('f_sales_line', sa.Column('cost_fifo', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('f_sales_line', 'cost_fifo')
    op.drop_column('f_sales_line', 'cost_moving_avg')
    # ### end Alembic commands ###
