"""maintenance migration controls

Revision ID: c2f7a9d4e6b1
Revises: e6a9c3f1b2d4
Create Date: 2026-08-09 22:00:20.670402

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c2f7a9d4e6b1"
down_revision: str | Sequence[str] | None = "e6a9c3f1b2d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute(
        """
        UPDATE sys_role_template
        SET permissions = CASE
                WHEN jsonb_typeof(permissions) = 'object' THEN permissions
                ELSE '{}'::jsonb
            END || jsonb_build_object(
                'action_maintenance_migration_review', code = 'admin'
            )
        """
    )
    op.execute(
        """
        UPDATE sys_user
        SET template_perms = template_perms || jsonb_build_object(
                'action_maintenance_migration_review', role = 'admin'
            ),
            perm_overrides = CASE
                    WHEN jsonb_typeof(perm_overrides) = 'object'
                    THEN perm_overrides
                    ELSE '{}'::jsonb
                END - 'action_maintenance_migration_review'
        WHERE jsonb_typeof(template_perms) = 'object'
        """
    )
    op.execute(
        """
        UPDATE sys_user
        SET permissions = CASE
                WHEN jsonb_typeof(permissions) = 'object' THEN permissions
                ELSE '{}'::jsonb
            END || jsonb_build_object(
                'action_maintenance_migration_review', role = 'admin'
            )
        WHERE permissions IS NOT NULL
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_migration_run",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "preview_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("manifest_key_id", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("reconciled_by", sa.String(length=64), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'previewed' AND reconciled_by IS NULL AND reconciled_at IS NULL AND approved_by IS NULL AND approved_at IS NULL AND manifest_json IS NULL AND manifest_hash IS NULL AND manifest_key_id IS NULL) OR (status = 'reconciled' AND reconciled_by IS NOT NULL AND reconciled_at IS NOT NULL AND approved_by IS NULL AND approved_at IS NULL AND manifest_json IS NULL AND manifest_hash IS NULL AND manifest_key_id IS NULL) OR (status = 'approved' AND reconciled_by IS NOT NULL AND reconciled_at IS NOT NULL AND approved_by IS NOT NULL AND approved_at IS NOT NULL AND manifest_json IS NOT NULL AND manifest_hash IS NOT NULL AND manifest_key_id IS NOT NULL)",
            name="ck_maintenance_migration_run_state_evidence",
        ),
        sa.CheckConstraint(
            "status IN ('previewed', 'reconciled', 'approved')",
            name="ck_maintenance_migration_run_status",
        ),
        sa.CheckConstraint(
            "approved_by IS NULL OR (approved_by <> created_by AND approved_by <> reconciled_by)",
            name="ck_maintenance_migration_run_independent_approval",
        ),
        sa.CheckConstraint(
            "char_length(btrim(created_by)) > 0 AND version >= 1",
            name="ck_maintenance_migration_run_identity",
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64 AND char_length(source_snapshot_hash) = 64 AND (manifest_hash IS NULL OR char_length(manifest_hash) = 64)",
            name="ck_maintenance_migration_run_hashes",
        ),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_maintenance_migration_run_status_time",
        "maintenance_migration_run",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "maintenance_migration_event",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("operation_key", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column(
            "payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("operated_by", sa.String(length=64), nullable=False),
        sa.Column(
            "operated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('preview', 'reconcile', 'approve')",
            name="ck_maintenance_migration_event_action",
        ),
        sa.CheckConstraint(
            "to_status IN ('previewed', 'reconciled', 'approved') AND (from_status IS NULL OR from_status IN ('previewed', 'reconciled'))",
            name="ck_maintenance_migration_event_status",
        ),
        sa.CheckConstraint(
            "char_length(btrim(operation_key)) > 0 AND char_length(btrim(reason)) > 0 AND char_length(btrim(operated_by)) > 0",
            name="ck_maintenance_migration_event_identity",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["maintenance_project.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["maintenance_migration_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("operation_key"),
    )
    op.create_index(
        "ix_maintenance_migration_event_run_time",
        "maintenance_migration_event",
        ["run_id", "operated_at", "event_id"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION reject_maintenance_migration_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'maintenance_migration_event is append-only';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_maintenance_migration_event_append_only
        BEFORE UPDATE OR DELETE ON maintenance_migration_event
        FOR EACH ROW
        EXECUTE FUNCTION reject_maintenance_migration_event_mutation()
        """
    )
    op.create_table(
        "maintenance_project_cutover_plan",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("cutover_date", sa.Date(), nullable=False),
        sa.Column("historical_mode", sa.String(length=32), nullable=False),
        sa.Column("source_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "historical_cost_ex_tax", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "historical_cost_inc_tax", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "post_cutover_cost_ex_tax",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "post_cutover_cost_inc_tax",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "approved_expense_ex_tax", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "approved_expense_inc_tax",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "total_cost_ex_tax", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "total_cost_inc_tax", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("blocker_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reconciled_by", sa.String(length=64), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciliation_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "historical_mode IN ('approved_cost_baseline', 'stable_site_issues')",
            name="ck_maintenance_project_cutover_historical_mode",
        ),
        sa.CheckConstraint(
            "status IN ('previewed', 'reconciled', 'approved')",
            name="ck_maintenance_project_cutover_status",
        ),
        sa.CheckConstraint(
            "blocker_count >= 0 AND version >= 1",
            name="ck_maintenance_project_cutover_counts",
        ),
        sa.CheckConstraint(
            "(status = 'previewed' AND reconciled_by IS NULL AND reconciled_at IS NULL AND reconciliation_reason IS NULL) OR (status IN ('reconciled', 'approved') AND reconciled_by IS NOT NULL AND reconciled_at IS NOT NULL AND char_length(btrim(reconciliation_reason)) > 0)",
            name="ck_maintenance_project_cutover_reconciliation",
        ),
        sa.CheckConstraint(
            "char_length(source_snapshot_hash) = 64 AND char_length(input_fingerprint) = 64",
            name="ck_maintenance_project_cutover_hashes",
        ),
        sa.CheckConstraint(
            "historical_cost_ex_tax >= 0 AND historical_cost_inc_tax >= 0 AND post_cutover_cost_ex_tax >= 0 AND post_cutover_cost_inc_tax >= 0 AND approved_expense_ex_tax >= 0 AND approved_expense_inc_tax >= 0 AND total_cost_ex_tax >= 0 AND total_cost_inc_tax >= 0",
            name="ck_maintenance_project_cutover_amounts",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["maintenance_project.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["maintenance_migration_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("plan_id"),
        sa.UniqueConstraint(
            "run_id", "project_id", name="uq_maintenance_project_cutover_run_project"
        ),
    )
    op.create_index(
        "ix_maintenance_project_cutover_project_time",
        "maintenance_project_cutover_plan",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "maintenance_historical_cost_baseline",
        sa.Column("baseline_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("amount_ex_tax", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_inc_tax", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("approval_state", sa.String(length=16), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(approval_state = 'pending' AND approved_by IS NULL AND approved_at IS NULL AND approval_reason IS NULL) OR (approval_state = 'approved' AND approved_by IS NOT NULL AND approved_at IS NOT NULL AND char_length(btrim(approval_reason)) > 0)",
            name="ck_maintenance_historical_baseline_approval",
        ),
        sa.CheckConstraint(
            "amount_ex_tax >= 0 AND amount_inc_tax >= 0",
            name="ck_maintenance_historical_baseline_amounts",
        ),
        sa.CheckConstraint(
            "char_length(evidence_hash) = 64 AND version >= 1",
            name="ck_maintenance_historical_baseline_identity",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["maintenance_project_cutover_plan.plan_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["maintenance_project.project_id"],
        ),
        sa.PrimaryKeyConstraint("baseline_id"),
        sa.UniqueConstraint("plan_id"),
    )
    op.create_table(
        "maintenance_inventory_opening_balance",
        sa.Column("opening_balance_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("balance_key", sa.String(length=256), nullable=False),
        sa.Column("pn", sa.String(length=256), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("approval_state", sa.String(length=16), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(approval_state = 'pending' AND approved_by IS NULL AND approved_at IS NULL AND approval_reason IS NULL) OR (approval_state = 'approved' AND approved_by IS NOT NULL AND approved_at IS NOT NULL AND char_length(btrim(approval_reason)) > 0)",
            name="ck_maintenance_inventory_opening_approval",
        ),
        sa.CheckConstraint(
            "char_length(evidence_hash) = 64 AND version >= 1",
            name="ck_maintenance_inventory_opening_identity",
        ),
        sa.CheckConstraint(
            "quantity >= 0 AND quantity < 1000000000000",
            name="ck_maintenance_inventory_opening_quantity",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["maintenance_project_cutover_plan.plan_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["maintenance_project.project_id"],
        ),
        sa.PrimaryKeyConstraint("opening_balance_id"),
        sa.UniqueConstraint(
            "plan_id", "balance_key", name="uq_maintenance_inventory_opening_plan_key"
        ),
    )
    op.create_index(
        "ix_maintenance_inventory_opening_project",
        "maintenance_inventory_opening_balance",
        ["project_id", "balance_key"],
        unique=False,
    )
    op.create_table(
        "maintenance_migration_discrepancy",
        sa.Column("discrepancy_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("stable_key", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "detail_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("resolved_by", sa.String(length=64), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'open' AND resolved_by IS NULL AND resolved_at IS NULL AND resolution_reason IS NULL) OR (status = 'resolved' AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL AND char_length(btrim(resolution_reason)) > 0)",
            name="ck_maintenance_migration_discrepancy_resolution",
        ),
        sa.CheckConstraint(
            "severity IN ('blocker', 'warning')",
            name="ck_maintenance_migration_discrepancy_severity",
        ),
        sa.CheckConstraint(
            "char_length(stable_key) = 64 AND version >= 1",
            name="ck_maintenance_migration_discrepancy_identity",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["maintenance_project_cutover_plan.plan_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["maintenance_project.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["maintenance_migration_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("discrepancy_id"),
        sa.UniqueConstraint(
            "plan_id", "stable_key", name="uq_maintenance_migration_discrepancy_key"
        ),
    )
    op.create_index(
        "ix_maintenance_migration_discrepancy_run_status",
        "maintenance_migration_discrepancy",
        ["run_id", "status", "severity"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute(
        "LOCK TABLE maintenance_migration_discrepancy, "
        "maintenance_inventory_opening_balance, "
        "maintenance_historical_cost_baseline, "
        "maintenance_project_cutover_plan, maintenance_migration_event, "
        "maintenance_migration_run IN ACCESS EXCLUSIVE MODE"
    )
    op.execute(
        """
        DO $migration$
        BEGIN
          IF EXISTS (SELECT 1 FROM maintenance_migration_run)
             OR EXISTS (SELECT 1 FROM maintenance_project_cutover_plan)
             OR EXISTS (SELECT 1 FROM maintenance_historical_cost_baseline)
             OR EXISTS (SELECT 1 FROM maintenance_inventory_opening_balance)
             OR EXISTS (SELECT 1 FROM maintenance_migration_discrepancy)
             OR EXISTS (SELECT 1 FROM maintenance_migration_event)
          THEN
            RAISE EXCEPTION
              'c2f7a9d4e6b1 downgrade blocked: migration control history is not empty';
          END IF;
        END
        $migration$;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_maintenance_migration_discrepancy_run_status",
        table_name="maintenance_migration_discrepancy",
    )
    op.drop_table("maintenance_migration_discrepancy")
    op.drop_index(
        "ix_maintenance_inventory_opening_project",
        table_name="maintenance_inventory_opening_balance",
    )
    op.drop_table("maintenance_inventory_opening_balance")
    op.drop_table("maintenance_historical_cost_baseline")
    op.drop_index(
        "ix_maintenance_project_cutover_project_time",
        table_name="maintenance_project_cutover_plan",
    )
    op.drop_table("maintenance_project_cutover_plan")
    op.drop_index(
        "ix_maintenance_migration_event_run_time",
        table_name="maintenance_migration_event",
    )
    op.execute(
        "DROP TRIGGER trg_maintenance_migration_event_append_only "
        "ON maintenance_migration_event"
    )
    op.execute("DROP FUNCTION reject_maintenance_migration_event_mutation()")
    op.drop_table("maintenance_migration_event")
    op.drop_index(
        "ix_maintenance_migration_run_status_time",
        table_name="maintenance_migration_run",
    )
    op.drop_table("maintenance_migration_run")
    op.execute(
        """
        UPDATE sys_role_template
        SET permissions = permissions - 'action_maintenance_migration_review'
        WHERE jsonb_typeof(permissions) = 'object'
        """
    )
    for column in ("template_perms", "permissions", "perm_overrides"):
        op.execute(
            f"""
            UPDATE sys_user
            SET {column} = {column} - 'action_maintenance_migration_review'
            WHERE jsonb_typeof({column}) = 'object'
            """
        )
    # ### end Alembic commands ###
