"""initial schema v1.1

Revision ID: fb60839c775d
Revises: 
Create Date: 2026-05-22 17:02:41.599581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb60839c775d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_raw', sa.String(length=256), nullable=False),
    sa.Column('name_normalized', sa.String(length=256), nullable=True),
    sa.Column('customer_type', sa.String(length=64), nullable=True),
    sa.Column('customer_source', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_raw')
    )
    op.create_index('ix_customer_norm', 'dim_customer', ['name_normalized'], unique=False)
    op.create_table('dim_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pn_std', sa.String(length=128), nullable=False),
    sa.Column('pn_raw_sample', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('category_major', sa.String(length=64), nullable=True),
    sa.Column('category_minor', sa.String(length=128), nullable=True),
    sa.Column('machine_or_part', sa.String(length=16), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pn_std')
    )
    op.create_table('dim_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_raw', sa.String(length=256), nullable=False),
    sa.Column('name_normalized', sa.String(length=256), nullable=True),
    sa.Column('supplier_code', sa.String(length=64), nullable=True),
    sa.Column('supplier_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_raw')
    )
    op.create_index('ix_supplier_norm', 'dim_supplier', ['name_normalized'], unique=False)
    op.create_table('part_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pn_raw', sa.String(length=256), nullable=False),
    sa.Column('pn_std', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='auto', nullable=False),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pn_raw')
    )
    op.create_index('ix_alias_std', 'part_alias', ['pn_std'], unique=False)
    op.create_table('sys_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('operated_by', sa.String(length=64), nullable=True),
    sa.Column('operated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rows_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_error', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_inactive', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='processing', nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_batch_success_hash', 'sys_import_batch', ['file_hash'], unique=True, postgresql_where=sa.text("status = 'success'"))
    op.create_table('f_part_inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_row_hash', sa.String(length=64), nullable=False),
    sa.Column('apply_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parts_type', sa.String(length=64), nullable=True),
    sa.Column('pn_raw', sa.String(length=256), nullable=True),
    sa.Column('pn_std', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('money', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['sys_import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_row_hash')
    )
    op.create_index('ix_inq_pn', 'f_part_inquiry', ['pn_std'], unique=False)
    op.create_table('f_purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_order_id', sa.String(length=64), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('purchaser', sa.String(length=64), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('linked_sales_order_no', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_type_raw', sa.String(length=64), nullable=True),
    sa.Column('amount_ex_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('data_status', sa.String(length=16), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['sys_import_batch.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['dim_supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_order_id')
    )
    op.create_index('ix_po_linked', 'f_purchase_order', ['linked_sales_order_no'], unique=False)
    op.create_index('ix_po_order_no', 'f_purchase_order', ['order_no'], unique=False)
    op.create_table('f_sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_order_id', sa.String(length=64), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('salesperson', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('business_type', sa.String(length=32), nullable=True),
    sa.Column('warehouse', sa.String(length=64), nullable=True),
    sa.Column('amount_ex_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('data_status', sa.String(length=16), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['sys_import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_order_id')
    )
    op.create_index('ix_so_order_no', 'f_sales_order', ['order_no'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_inventory_id', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('pn_std', sa.String(length=128), nullable=False),
    sa.Column('warehouse', sa.String(length=64), nullable=False),
    sa.Column('source_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('manual_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('is_qty_overridden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('machine_or_part', sa.String(length=16), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('inventory_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['sys_import_batch.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['dim_part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pn_std', 'warehouse', name='uq_inventory_pn_wh'),
    sa.UniqueConstraint('raw_inventory_id')
    )
    op.create_table('part_substitute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id_a', sa.Integer(), nullable=False),
    sa.Column('part_id_b', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('part_id_a < part_id_b', name='ck_substitute_order'),
    sa.ForeignKeyConstraint(['part_id_a'], ['dim_part.id'], ),
    sa.ForeignKeyConstraint(['part_id_b'], ['dim_part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id_a', 'part_id_b', name='uq_substitute_pair')
    )
    op.create_table('sys_import_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=32), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['sys_import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_raw_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['sys_import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('f_purchase_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_line_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('pn_std', sa.String(length=128), nullable=True),
    sa.Column('pn_raw', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('machine_or_part', sa.String(length=16), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('recent_purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('anomaly_flags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['sys_import_batch.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['f_purchase_order.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['dim_part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_line_id')
    )
    op.create_index('ix_pl_part', 'f_purchase_line', ['part_id'], unique=False)
    op.create_index('ix_pl_pn', 'f_purchase_line', ['pn_std'], unique=False)
    op.create_table('f_sales_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_line_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('pn_std', sa.String(length=128), nullable=True),
    sa.Column('pn_raw', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('category_major', sa.String(length=64), nullable=True),
    sa.Column('category_minor', sa.String(length=128), nullable=True),
    sa.Column('machine_or_part', sa.String(length=16), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('generic_product', sa.String(length=256), nullable=True),
    sa.Column('serial_numbers', sa.Text(), nullable=True),
    sa.Column('matched_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_source', sa.String(length=16), nullable=True),
    sa.Column('revenue_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('counts_revenue', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('anomaly_flags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['sys_import_batch.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['f_sales_order.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['dim_part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_line_id')
    )
    op.create_index('ix_sl_flags', 'f_sales_line', ['anomaly_flags'], unique=False, postgresql_using='gin')
    op.create_index('ix_sl_part', 'f_sales_line', ['part_id'], unique=False)
    op.create_index('ix_sl_pn', 'f_sales_line', ['pn_std'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sl_pn', table_name='f_sales_line')
    op.drop_index('ix_sl_part', table_name='f_sales_line')
    op.drop_index('ix_sl_flags', table_name='f_sales_line', postgresql_using='gin')
    op.drop_table('f_sales_line')
    op.drop_index('ix_pl_pn', table_name='f_purchase_line')
    op.drop_index('ix_pl_part', table_name='f_purchase_line')
    op.drop_table('f_purchase_line')
    op.drop_table('sys_raw_file')
    op.drop_table('sys_import_error')
    op.drop_table('part_substitute')
    op.drop_table('inventory')
    op.drop_index('ix_so_order_no', table_name='f_sales_order')
    op.drop_table('f_sales_order')
    op.drop_index('ix_po_order_no', table_name='f_purchase_order')
    op.drop_index('ix_po_linked', table_name='f_purchase_order')
    op.drop_table('f_purchase_order')
    op.drop_index('ix_inq_pn', table_name='f_part_inquiry')
    op.drop_table('f_part_inquiry')
    op.drop_index('ux_batch_success_hash', table_name='sys_import_batch', postgresql_where=sa.text("status = 'success'"))
    op.drop_table('sys_import_batch')
    op.drop_table('sys_audit_log')
    op.drop_index('ix_alias_std', table_name='part_alias')
    op.drop_table('part_alias')
    op.drop_index('ix_supplier_norm', table_name='dim_supplier')
    op.drop_table('dim_supplier')
    op.drop_table('dim_part')
    op.drop_index('ix_customer_norm', table_name='dim_customer')
    op.drop_table('dim_customer')
    # ### end Alembic commands ###
