#!/usr/bin/env bash
# 当前 schema 恢复门禁：隔离恢复最新备份，逐表比对关键事实后删除临时库。
# 历史 v1.20 有独立的 exact-SHA 恢复控制面，不调用本脚本。
set -Eeuo pipefail
umask 077
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
APP_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd -P)
cd "$APP_DIR"

fatal() {
  printf 'FATAL: %s\n' "$*" >&2
  exit 1
}

dc() {
  sudo docker compose exec -T db "$@"
}

# The backup filenames are generated by this project and contain no newlines.
# shellcheck disable=SC2012
DUMP=$(ls -t /var/backups/spareparts/db-*.dump | head -1)
[ -f "$DUMP" ] || fatal "no backup dump found"
[ -f "$DUMP.sha256" ] || fatal "backup checksum missing"
printf '恢复演练用最新备份: %s\n' "$DUMP"
sha256sum -c "$DUMP.sha256"
dc pg_restore --list < "$DUMP" >/dev/null

SOURCE_COUNTS=$(mktemp)
RESTORED_COUNTS=$(mktemp)
RESTORE_CREATED=0
cleanup() {
  status=$?
  trap - EXIT INT TERM
  if [ "$RESTORE_CREATED" = 1 ]; then
    dc psql -U spareparts -d postgres -v ON_ERROR_STOP=1 \
      -c "DROP DATABASE restore_test;" >/dev/null || status=97
  fi
  rm -f -- "$SOURCE_COUNTS" "$RESTORED_COUNTS" || status=97
  exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

[ "$(dc psql -U spareparts -d postgres -v ON_ERROR_STOP=1 -At \
  -c "SELECT count(*) FROM pg_database WHERE datname='restore_test';")" = 0 ] \
  || fatal "restore_test already exists"
dc psql -U spareparts -d postgres -v ON_ERROR_STOP=1 \
  -c "CREATE DATABASE restore_test;" >/dev/null
RESTORE_CREATED=1

SOURCE_DB_HEAD=$(dc psql -U spareparts -d spareparts -v ON_ERROR_STOP=1 -At \
  -c "SELECT version_num FROM alembic_version;")

COUNT_SQL="SELECT 'dim_part|' || count(*) FROM dim_part
UNION ALL SELECT 'f_maintenance_line|' || count(*) FROM f_maintenance_line
UNION ALL SELECT 'f_project_expense|' || count(*) FROM f_project_expense
UNION ALL SELECT 'f_purchase_line|' || count(*) FROM f_purchase_line
UNION ALL SELECT 'f_sales_line|' || count(*) FROM f_sales_line
UNION ALL SELECT 'maintenance_project|' || count(*) FROM maintenance_project
UNION ALL SELECT 'maintenance_project_contract|' || count(*) FROM maintenance_project_contract
UNION ALL SELECT 'sys_import_batch|' || count(*) FROM sys_import_batch
ORDER BY 1;"

dc psql -U spareparts -d spareparts -v ON_ERROR_STOP=1 -At \
  -c "$COUNT_SQL" > "$SOURCE_COUNTS"

dc pg_restore -U spareparts -d restore_test --exit-on-error \
  --no-owner < "$DUMP"
RESTORED_DB_HEAD=$(dc psql -U spareparts -d restore_test -v ON_ERROR_STOP=1 -At \
  -c "SELECT version_num FROM alembic_version;")
[ "$RESTORED_DB_HEAD" = "$SOURCE_DB_HEAD" ] \
  || fatal "restored database head differs from source"

dc psql -U spareparts -d restore_test -v ON_ERROR_STOP=1 -At \
  -c "$COUNT_SQL" > "$RESTORED_COUNTS"
diff -u "$SOURCE_COUNTS" "$RESTORED_COUNTS"

printf '%s\n' "恢复成功：数据库 head 一致，关键事实表（含两张稳定维保项目表）逐表行数一致"
